const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.List,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.TelegramMiniAppsSDK,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.ScriptsInEvents.Es_main_Event1_Act1,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TelegramMiniAppsSDK.Exps.UserId,
		C3.Plugins.TelegramMiniAppsSDK.Exps.UserFirstName,
		C3.Plugins.TelegramMiniAppsSDK.Exps.UserLanguageCode,
		C3.Plugins.TelegramMiniAppsSDK.Exps.UserLastName,
		C3.Plugins.TelegramMiniAppsSDK.Exps.UserUsername,
		C3.Plugins.TelegramMiniAppsSDK.Exps.Version,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TelegramMiniAppsSDK.Cnds.OnGetChatMemberSuccess,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowAlert,
		C3.Plugins.Button.Cnds.CompareInstanceVar,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.TelegramMiniAppsSDK.Cnds.OnGetChatMemberError,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowConfirm,
		C3.Plugins.TelegramMiniAppsSDK.Cnds.OnConfirmOK,
		C3.Plugins.TelegramMiniAppsSDK.Cnds.IsInTelegram,
		C3.Plugins.TelegramMiniAppsSDK.Acts.OpenTelegramLink,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TelegramMiniAppsSDK.Acts.GetChatMember,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TelegramMiniAppsSDK.Acts.OnSelectionChanged,
		C3.Plugins.Button.Cnds.PickChildren,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ImpactOccurred,
		C3.Plugins.TelegramMiniAppsSDK.Acts.NotificationOccurred,
		C3.Plugins.TelegramMiniAppsSDK.Acts.CloseMiniApp,
		C3.Plugins.TelegramMiniAppsSDK.Acts.Expand,
		C3.Plugins.TelegramMiniAppsSDK.Acts.OpenLink,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShareToStory,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowScanQrPopup,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowBackButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.HideBackButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowMainButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.HideMainButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.DisableMainButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.EnableMainButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowMainButtonProgress,
		C3.Plugins.TelegramMiniAppsSDK.Acts.HideMainButtonProgress,
		C3.Plugins.TelegramMiniAppsSDK.Acts.ShowSettingsButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.HideSettingsButton,
		C3.Plugins.TelegramMiniAppsSDK.Exps.BiometricDeviceId,
		C3.Plugins.TelegramMiniAppsSDK.Exps.BiometricType,
		C3.Plugins.TelegramMiniAppsSDK.Exps.IsBiometricAvailable,
		C3.Plugins.TelegramMiniAppsSDK.Exps.IsBiometricAccessGranted,
		C3.Plugins.TelegramMiniAppsSDK.Exps.IsBiometricAccessRequested,
		C3.Plugins.TelegramMiniAppsSDK.Exps.IsBiometricInited,
		C3.Plugins.TelegramMiniAppsSDK.Exps.IsBiometricTokenSaved,
		C3.Plugins.TelegramMiniAppsSDK.Cnds.OnBiometricManagerInited,
		C3.Plugins.TelegramMiniAppsSDK.Cnds.OnClickBackButton,
		C3.Plugins.TelegramMiniAppsSDK.Acts.InitBiometricManager,
		C3.Plugins.TelegramMiniAppsSDK.Acts.RequestAccessBiometricManager,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TelegramMiniAppsSDK.Acts.AuthenticateBiometricManager,
		C3.Plugins.TelegramMiniAppsSDK.Acts.OpenSettingsBiometricManager,
		C3.Plugins.TelegramMiniAppsSDK.Acts.UpdateBiometricToken,
		C3.Plugins.TelegramMiniAppsSDK.Acts.CloudStorageSetItem,
		C3.Plugins.TelegramMiniAppsSDK.Acts.CloudStorageRemoveItem,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.TelegramMiniAppsSDK.Exps.CloudStorageValue
	];
};
self.C3_JsPropNameTable = [
	{Name: 0},
	{Button: 0},
	{Text: 0},
	{Browser: 0},
	{List: 0},
	{Touch: 0},
	{TextInput: 0},
	{Logs: 0},
	{TelegramMiniAppsSDK: 0},
	{BOT_API_TOKEN: 0}
];

self.InstanceType = {
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	List: class extends self.IListInstance {},
	Touch: class extends self.IInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Logs: class extends self.ITextInputInstance {},
	TelegramMiniAppsSDK: class extends self.C3.Plugins.TelegramMiniAppsSDK.Instance {}
}